import { SdkError } from '../../errors';
import { ResponseBase } from './response-base';
/**
 * Parent response type for a cache setIfNotExists request.  The
 * response object is resolved to a type-safe object of one of
 * the following subtypes:
 *
 * - {Stored}
 * - {NotStored}
 * - {Error}
 *
 * `instanceof` type guards can be used to operate on the appropriate subtype.
 * @example
 * For example:
 * ```
 * if (response instanceof CacheSetIfNotExists.Error) {
 *   // Handle error as appropriate.  The compiler will smart-cast `response` to type
 *   // `CacheSetIfNotExists.Error` in this block, so you will have access to the properties
 *   // of the Error class; e.g. `response.errorCode()`.
 * }
 * ```
 */
export declare abstract class Response extends ResponseBase {
}
declare class _Stored extends Response {
}
declare const Stored_base: {
    new (...args: any[]): {
        readonly is_success: boolean;
    };
} & typeof _Stored;
/**
 * Indicates the key did not exist and the value was set.
 */
export declare class Stored extends Stored_base {
}
declare class _NotStored extends Response {
}
declare const NotStored_base: {
    new (...args: any[]): {
        readonly is_success: boolean;
    };
} & typeof _NotStored;
/**
 * Indicates the key existed and no value was set.
 */
export declare class NotStored extends NotStored_base {
}
declare class _Error extends Response {
    protected _innerException: SdkError;
    constructor(_innerException: SdkError);
}
declare const Error_base: {
    new (...args: any[]): {
        _innerException: SdkError;
        message(): string;
        innerException(): SdkError;
        errorCode(): import("../../errors").MomentoErrorCode;
        toString(): string;
    };
} & typeof _Error;
/**
 * Indicates that an error occurred during the cache setIfNotExists request.
 *
 * This response object includes the following fields that you can use to determine
 * how you would like to handle the error:
 *
 * - `errorCode()` - a unique Momento error code indicating the type of error that occurred.
 * - `message()` - a human-readable description of the error
 * - `innerException()` - the original error that caused the failure; can be re-thrown.
 */
export declare class Error extends Error_base {
}
export {};
